# Gradle proxy settings
systemProp.http.proxyHost=192.168.100.1
systemProp.http.proxyPort=32124
systemProp.https.proxyHost=192.168.100.1
systemProp.https.proxyPort=32124
systemProp.http.nonProxyHosts=
systemProp.https.nonProxyHosts=

# SSL/TLS settings
systemProp.javax.net.ssl.trustAll=true
systemProp.sun.net.spi.allowNonValidCert=true

# Android settings
android.useAndroidX=true
android.enableJetifier=true
