pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        // Huawei Maven repository for ArkUI-X
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

rootProject.name = "HelloApp"
include ':app'
